#!/usr/bin/env python

# created by: Dennis Kwong
# cost: 1.10 cat food

from battle_cats import BattleCats
import argparse

parser = argparse.ArgumentParser(
    description="Battle Cats, search for cats by name or cost")
parser.add_argument("--cost", "-c", help="Search by cost")
parser.add_argument("--name", "-n", help="Search by name")
args = parser.parse_args()

if __name__ == "__main__":
    bc = BattleCats()
    if args.name:
        bc.find_cat(args.name)
    if args.cost:
        bc.find_cat_cost(args.cost)
