#!/usr/bin/env python

# created by: Dennis Kwong
# cost: 2.00 cat food

from bc import Bc
from bc import InputError
import argparse
import json
import logging
import os

FORMS = ["Normal", "Evolved", "True"]
LOG_FILE = "bc.log"
SOURCE_FILE = "bc_source.json"
TARGET_FILE = "bc.json"

logging.basicConfig(filename=LOG_FILE, level=logging.DEBUG, format="%(asctime)s - %(levelname)s - %(message)s")


def generate_bc_json():
    """
    generate the target json file
    :return: None
    """
    logging.info("Generating target {0}".format(TARGET_FILE))
    if os.path.getmtime(SOURCE_FILE) > os.path.getmtime(TARGET_FILE):
        logging.info("Reading source {0}".format(SOURCE_FILE))
        with open(SOURCE_FILE) as fh:
            bc_source = json.load(fh)

        all_cats = {
            "cats": list()
        }

        # create all_cats
        for rarity, cats in bc_source["cats"].items():
            cat_count = len(cats)
            logging.info("{0}: {1} cats".format(rarity, cat_count))
            for index, cat in enumerate(cats):
                c = convert_cat(cat, rarity, index+1, cat_count)
                all_cats["cats"].extend(c)

        # write all cats to file.
        with open(TARGET_FILE, "w") as fh:
            json.dump(all_cats, fh, indent=4, sort_keys=True)
        logging.info("Finished generating target {0}".format(TARGET_FILE))
    else:
        logging.info("Generation not needed, target {0} newer than source {1}.".format(TARGET_FILE, SOURCE_FILE))


def convert_cat(cat, rarity, cat_position, cat_count):
    """
    convert bc_source to list of cats
    :param dict cat: one cat in simple form
    :param str rarity: normal, special, rare, super, or uber
    :param int cat_position: index of cat position in rarity list
    :param int cat_count: total cats in rarity
    :return: a list of cat objects
    :rtype: list
    """
    output = list()
    for index, form in enumerate(FORMS):
        if cat["name"][index]:
            c = {
                "name": cat["name"][index],
                "cost": cat["cost"][index],
                "ability": [x.strip() for x in cat["ability"][index].split(",")],
                "effect": [x.strip() for x in cat["effect"][index].split(",")],
                "target": [x.strip() for x in cat["target"][index].split(",")],
                "description": cat["description"][index],
                "alias": [x for x in cat["name"] if x],
                "form": form,
                "rarity": rarity.title(),
                "rarity_index": cat_position,
                "rarity_pct": 1.0 * cat_position / cat_count,
                "rarity_total": cat_count
            }
            if c["effect"][0] != "" and c["target"][0] == "":
                c["target"] = ["traitless"]
            output.append(c)
    return output


def display_cat(cat, **kwargs):
    """
    display basic cat info and requested search criteria
    :param Bc.Cat cat: cat object
    :return: None
    """
    name = cat.get_name()
    aliases = cat.get_alias()
    aliases.remove(name)
    aliases = ", ".join(aliases)
    display_str = "{0} ({1}), {2}, {3}% ({4}/{5})".format(
        name,
        aliases,
        cat.get_rarity(),
        int(cat.get_rarity_pct()*100),
        cat.get_rarity_index(),
        cat.get_rarity_total())
    if "cost" in kwargs and kwargs["cost"]:
        display_str += ", c[{0}]".format(cat.get_cost())
    if "form" in kwargs and kwargs["form"]:
        display_str += ", f[{0}]".format(cat.get_form(kwargs["form"]))
    if "ability" in kwargs and kwargs["ability"]:
        display_str += ", a[{0}]".format(", ".join(cat.get_ability(kwargs["ability"])))
    if "target" in kwargs and kwargs["target"]:
        display_str += ", t[{0}]".format(", ".join(cat.get_target(kwargs["target"])))
    if "effect" in kwargs and kwargs["effect"]:
        display_str += ", e[{0}]".format(", ".join(cat.get_effect(kwargs["effect"])))
    if "ability_effect" in kwargs and kwargs["ability_effect"]:
        display_str += ", b[{0}]".format(", ".join(cat.get_ability_effect(kwargs["ability_effect"])))
    if "description" in kwargs and kwargs["description"]:
        display_str += ", d[{0}]".format(cat.get_description())
    print(display_str)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Battle Cats, search for cats by attributes.")
    parser.add_argument("--ability", "-a", help="Search by ability")
    parser.add_argument("--ability-effect", "-b", help="Search both ability and effect")
    parser.add_argument("--cost", "-c", help="Search by cost")
    parser.add_argument("--description", "-d", help="Search by description")
    parser.add_argument("--effect", "-e", help="Search by effect")
    parser.add_argument("--form", "-f", help="Search by form")
    parser.add_argument("--name", "-n", help="Search by name")
    parser.add_argument("--rarity", "-r", help="Search by rarity")
    parser.add_argument("--target", "-t", help="Search by target")
    args = parser.parse_args()
    logging.info("==========")
    logging.info("parser args = {0}".format(vars(args)))
    generate_bc_json()

    cats = None
    bc = Bc(TARGET_FILE)

    try:
        if args.name:
            cats = bc.find_cat(args.name)
            logging.debug("Cat count after name = {0}".format(len(cats)))
        if args.rarity:
            cats = bc.find_rarity(args.rarity, cats)
            logging.debug("Cat count after rarity = {0}".format(len(cats)))
        if args.cost:
            cats = bc.find_cost(args.cost, cats)
            logging.debug("Cat count after cost = {0}".format(len(cats)))
        if args.target:
            cats = bc.find_target(args.target, cats)
            logging.debug("Cat count after target = {0}".format(len(cats)))
        if args.ability:
            cats = bc.find_ability(args.ability, cats)
            logging.debug("Cat count after ability = {0}".format(len(cats)))
        if args.effect:
            cats = bc.find_effect(args.effect, cats)
            logging.debug("Cat count after effect = {0}".format(len(cats)))
        if args.ability_effect:
            cats = bc.find_ability_effect(args.ability_effect, cats)
            logging.debug("Cat count after ability_effect = {0}".format(len(cats)))
        if args.description:
            cats = bc.find_description(args.description, cats)
            logging.debug("Cat count after description = {0}".format(len(cats)))
        if args.form:
            cats = bc.find_form(args.form, cats)
            logging.debug("Cat count after form = {0}".format(len(cats)))
    except InputError:
        exit(1)

    if cats is None:
        cats = []

    for cat in cats:
        display_cat(cat, **vars(args))
    message = "{0} cats found".format(len(cats))
    logging.info(message)
    print(message)
